const featured = [['$1.9M','Traumatic brain injury caused by lack of supervision'],['$1.5M','Fall resulting in disabling injuries'],['$900K','Moped accident']];
const moreResults = [['$850,000','Burn injury'],['$600,000','Tractor-trailer crash requiring back surgery'],['$400,000','Pedestrian struck; facial and hand fractures'],['$300,000','Elevator accident'],['$300,000','Trip and fall requiring multiple hip surgeries'],['$290,000','Dog bite injuries and psychological damages'],['$275,000','Car accident with back and psychological injuries'],['$275,000','City park trip and fall requiring surgery']];
const injuryAreas = ['Car & truck accidents','Pedestrian accidents','Slip, trip & falls','Construction accidents','Dog bites','Serious & catastrophic injuries'];
export default function Home(){return <main>
  <div className="notice">Serving Staten Island and the New York metropolitan area</div>
  <header className="site-header"><a className="brand" href="#top" aria-label="Law Office of Christopher Dai home"><span className="brand-mark">CD</span><span><strong>Christopher Dai</strong><small>Attorney at Law</small></span></a><nav aria-label="Primary navigation"><a href="#practice">Practice Areas</a><a href="#results">Case Results</a><a href="#about">About</a><a href="#contact">Contact</a></nav><a className="header-call" href="tel:+17184470400"><small>Free consultation</small>(718) 447-0400</a></header>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">Personal Injury • Real Estate</p><h1>Personal attention.<br/><em>Proven results.</em></h1><p className="hero-lede">When an injury changes your life, you deserve an advocate who listens, responds, and fights for the result you need.</p><div className="hero-actions"><a className="button primary" href="tel:+17184470400">Discuss your case</a><a className="text-link" href="#results">View case results <span>→</span></a></div><div className="trust-row"><div><strong>100+</strong><span>5-star reviews</span></div><div><strong>$6.8M+</strong><span>featured results</span></div><div><strong>NY</strong><span>Local counsel</span></div></div></div><aside className="hero-panel" aria-label="Featured case results"><p className="panel-label">Featured case results</p>{featured.map(([a,l])=><div className="result-mini" key={a}><strong>{a}</strong><span>{l}</span></div>)}<a href="#results">See all results</a></aside></section>
  <section className="practice-preview" id="practice"><div><p className="eyebrow dark">An integrated practice</p><h2>One trusted attorney.<br/>Two essential areas of law.</h2></div><article><span>01</span><h3>Personal Injury</h3><p>Serious representation for accident victims and their families.</p><a href="#injury">Explore injury cases →</a></article><article className="secondary"><span>02</span><h3>Real Estate</h3><p>Clear, careful guidance for residential and commercial transactions.</p><a href="#real-estate">Explore real estate →</a></article></section>
  <section className="injury-section" id="injury"><div className="section-heading"><p className="eyebrow dark">Injury representation</p><h2>Your recovery deserves<br/>our full attention.</h2><p>Insurance companies act quickly to protect themselves. The Law Office of Christopher Dai helps injured New Yorkers protect their rights, understand their options, and pursue meaningful compensation.</p><a className="button navy" href="#contact">Request a free consultation</a></div><div className="area-list">{injuryAreas.map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></section>
  <section className="results-section" id="results"><div className="results-intro"><p className="eyebrow">Selected case results</p><h2>Results that<br/>changed lives.</h2><p>Every case is different. These prior results do not guarantee a similar outcome.</p></div><div className="results-grid">{featured.map(([a,l])=><article key={a}><strong>{a}</strong><p>{l}</p></article>)}</div><details className="more-results"><summary>View additional case results <span>+</span></summary><div>{moreResults.map(([a,l])=><article key={a+l}><strong>{a}</strong><p>{l}</p></article>)}</div></details></section>
  <section className="real-estate" id="real-estate"><div className="re-number">02</div><div><p className="eyebrow dark">Real estate counsel</p><h2>From contract<br/>to closing.</h2></div><div><p>Whether you are buying, selling, financing, or investing, careful legal guidance helps protect the transaction and your peace of mind.</p><ul><li>Residential purchases and sales</li><li>Commercial transactions</li><li>Contract review and negotiation</li><li>Closing representation</li></ul><a className="text-link dark-link" href="#contact">Speak with the office <span>→</span></a></div></section>
  <section className="about" id="about"><div className="monogram">CD</div><div><p className="eyebrow">Your attorney</p><h2>Direct counsel.<br/>Personal service.</h2><p>Christopher Dai provides responsive, practical legal representation to individuals, families, and businesses throughout Staten Island and the New York metropolitan area. Clients work directly with the attorney handling their matter—from the first conversation through resolution or closing.</p><blockquote>“Legal matters are personal. Your representation should be, too.”</blockquote></div><div className="review-card"><div className="stars">★★★★★</div><strong>More than 100 five-star reviews</strong><p>Across Google and Avvo</p><span>Client feedback reflects a commitment to communication, diligence, and service.</span></div></section>
  <section className="contact" id="contact"><div><p className="eyebrow">Start a conversation</p><h2>Tell us how<br/>we can help.</h2><p>For a free personal injury consultation or to discuss a real estate matter, contact the office directly.</p></div><div className="contact-details"><a href="tel:+17184470400"><small>Telephone</small>(718) 447-0400</a><a href="mailto:cdailaw@aol.com"><small>Email</small>cdailaw@aol.com</a><address><small>Office</small>262 Nelson Avenue<br/>Staten Island, NY 10308</address></div><a className="circle-call" href="tel:+17184470400"><span>Call now</span>↗</a></section>
  <footer><div className="footer-brand"><span className="brand-mark">CD</span><p>Law Office of Christopher Dai, Esq.</p></div><div><p>Tel: <a href="tel:+17184470400">(718) 447-0400</a><br/>Fax: (718) 709-5882</p></div><div className="disclaimer"><p><strong>Attorney Advertising.</strong> Prior results do not guarantee a similar outcome. This website is for general information only and does not create an attorney-client relationship. Do not send confidential or time-sensitive information by email.</p><p>© 2026 Law Office of Christopher Dai, Esq.</p></div></footer>
  <a className="mobile-call" href="tel:+17184470400">Call for a free consultation</a>
 </main>}
